import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * Paint Products Seed Data
 * Real paint brands with realistic color collections
 */

const paintProducts = [
  // ========== SIKKENS ==========
  {
    brand: 'Sikkens',
    name: 'Alpha Rezisto',
    colorCode: 'F2.02.50',
    colorName: 'Warm Wit',
    hexColor: '#F5F3EF',
    rgb: JSON.stringify({ r: 245, g: 243, b: 239 }),
    finish: 'Mat',
    productLine: 'Alpha Rezisto',
    type: 'Interior',
    coverage: 12,
    price: 45.95,
    popular: true,
    inStock: true,
  },
  {
    brand: 'Sikkens',
    name: 'Alpha Rezisto',
    colorCode: 'L1.05.85',
    colorName: 'Licht Grijs',
    hexColor: '#E8E8E8',
    rgb: JSON.stringify({ r: 232, g: 232, b: 232 }),
    finish: 'Mat',
    productLine: 'Alpha Rezisto',
    type: 'Interior',
    coverage: 12,
    price: 45.95,
    popular: true,
    inStock: true,
  },
  {
    brand: 'Sikkens',
    name: 'Alpha Rezisto',
    colorCode: 'E0.10.70',
    colorName: 'Zacht Beige',
    hexColor: '#EAE6E0',
    rgb: JSON.stringify({ r: 234, g: 230, b: 224 }),
    finish: 'Zijdeglans',
    productLine: 'Alpha Rezisto',
    type: 'Interior',
    coverage: 12,
    price: 48.95,
    popular: true,
    inStock: true,
  },
  {
    brand: 'Sikkens',
    name: 'Alpha Rezisto',
    colorCode: 'D0.20.60',
    colorName: 'Zand',
    hexColor: '#DDD5CA',
    rgb: JSON.stringify({ r: 221, g: 213, b: 202 }),
    finish: 'Mat',
    productLine: 'Alpha Rezisto',
    type: 'Interior',
    coverage: 12,
    price: 45.95,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Sikkens',
    name: 'Alpha Rezisto',
    colorCode: 'B8.15.55',
    colorName: 'Licht Blauw',
    hexColor: '#C5D7E0',
    rgb: JSON.stringify({ r: 197, g: 215, b: 224 }),
    finish: 'Mat',
    productLine: 'Alpha Rezisto',
    type: 'Interior',
    coverage: 12,
    price: 45.95,
    popular: false,
    inStock: true,
  },

  // ========== SIGMA ==========
  {
    brand: 'Sigma',
    name: 'Sigma S3000',
    colorCode: 'S 0500-N',
    colorName: 'Pure White',
    hexColor: '#FFFFFF',
    rgb: JSON.stringify({ r: 255, g: 255, b: 255 }),
    finish: 'Mat',
    productLine: 'S3000',
    type: 'Interior',
    coverage: 10,
    price: 42.50,
    popular: true,
    inStock: true,
  },
  {
    brand: 'Sigma',
    name: 'Sigma S3000',
    colorCode: 'S 1002-Y',
    colorName: 'Creme Wit',
    hexColor: '#F8F6F0',
    rgb: JSON.stringify({ r: 248, g: 246, b: 240 }),
    finish: 'Mat',
    productLine: 'S3000',
    type: 'Interior',
    coverage: 10,
    price: 42.50,
    popular: true,
    inStock: true,
  },
  {
    brand: 'Sigma',
    name: 'Sigma S3000',
    colorCode: 'S 2005-Y20R',
    colorName: 'Licht Beige',
    hexColor: '#E5DDD1',
    rgb: JSON.stringify({ r: 229, g: 221, b: 209 }),
    finish: 'Zijdeglans',
    productLine: 'S3000',
    type: 'Interior',
    coverage: 10,
    price: 45.50,
    popular: true,
    inStock: true,
  },
  {
    brand: 'Sigma',
    name: 'Sigma S3000',
    colorCode: 'S 3005-Y80R',
    colorName: 'Warm Taupe',
    hexColor: '#C8BFB7',
    rgb: JSON.stringify({ r: 200, g: 191, b: 183 }),
    finish: 'Mat',
    productLine: 'S3000',
    type: 'Interior',
    coverage: 10,
    price: 42.50,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Sigma',
    name: 'Sigma S3000',
    colorCode: 'S 2502-B',
    colorName: 'Licht Grijs Blauw',
    hexColor: '#D5D8DC',
    rgb: JSON.stringify({ r: 213, g: 216, b: 220 }),
    finish: 'Mat',
    productLine: 'S3000',
    type: 'Interior',
    coverage: 10,
    price: 42.50,
    popular: false,
    inStock: true,
  },

  // ========== TRIMETAL ==========
  {
    brand: 'Trimetal',
    name: 'Histor Perfect Finish',
    colorCode: '6213',
    colorName: 'Sneeuw Wit',
    hexColor: '#FAFAFA',
    rgb: JSON.stringify({ r: 250, g: 250, b: 250 }),
    finish: 'Mat',
    productLine: 'Perfect Finish',
    type: 'Interior',
    coverage: 11,
    price: 39.95,
    popular: true,
    inStock: true,
  },
  {
    brand: 'Trimetal',
    name: 'Histor Perfect Finish',
    colorCode: '6204',
    colorName: 'Zacht Linen',
    hexColor: '#F2EDE4',
    rgb: JSON.stringify({ r: 242, g: 237, b: 228 }),
    finish: 'Mat',
    productLine: 'Perfect Finish',
    type: 'Interior',
    coverage: 11,
    price: 39.95,
    popular: true,
    inStock: true,
  },
  {
    brand: 'Trimetal',
    name: 'Histor Perfect Finish',
    colorCode: '7527',
    colorName: 'Zacht Grijs',
    hexColor: '#E0E0E0',
    rgb: JSON.stringify({ r: 224, g: 224, b: 224 }),
    finish: 'Zijdeglans',
    productLine: 'Perfect Finish',
    type: 'Interior',
    coverage: 11,
    price: 42.95,
    popular: true,
    inStock: true,
  },
  {
    brand: 'Trimetal',
    name: 'Histor Perfect Finish',
    colorCode: '6226',
    colorName: 'Cappuccino',
    hexColor: '#D4C5B3',
    rgb: JSON.stringify({ r: 212, g: 197, b: 179 }),
    finish: 'Mat',
    productLine: 'Perfect Finish',
    type: 'Interior',
    coverage: 11,
    price: 39.95,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Trimetal',
    name: 'Histor Perfect Finish',
    colorCode: '7510',
    colorName: 'Misty Blue',
    hexColor: '#C8D5DC',
    rgb: JSON.stringify({ r: 200, g: 213, b: 220 }),
    finish: 'Mat',
    productLine: 'Perfect Finish',
    type: 'Interior',
    coverage: 11,
    price: 39.95,
    popular: false,
    inStock: true,
  },

  // ========== HERBOL ==========
  {
    brand: 'Herbol',
    name: 'Herbol Profi-DIN',
    colorCode: '001',
    colorName: 'Brilliant White',
    hexColor: '#FCFCFC',
    rgb: JSON.stringify({ r: 252, g: 252, b: 252 }),
    finish: 'Mat',
    productLine: 'Profi-DIN',
    type: 'Interior',
    coverage: 13,
    price: 52.95,
    popular: true,
    inStock: true,
  },
  {
    brand: 'Herbol',
    name: 'Herbol Profi-DIN',
    colorCode: '056',
    colorName: 'Natural White',
    hexColor: '#F5F1EB',
    rgb: JSON.stringify({ r: 245, g: 241, b: 235 }),
    finish: 'Mat',
    productLine: 'Profi-DIN',
    type: 'Interior',
    coverage: 13,
    price: 52.95,
    popular: true,
    inStock: true,
  },
  {
    brand: 'Herbol',
    name: 'Herbol Profi-DIN',
    colorCode: '142',
    colorName: 'Warm Grey',
    hexColor: '#DCDCDC',
    rgb: JSON.stringify({ r: 220, g: 220, b: 220 }),
    finish: 'Zijdeglans',
    productLine: 'Profi-DIN',
    type: 'Interior',
    coverage: 13,
    price: 55.95,
    popular: true,
    inStock: true,
  },
  {
    brand: 'Herbol',
    name: 'Herbol Profi-DIN',
    colorCode: '089',
    colorName: 'Sand Beige',
    hexColor: '#E8E4DC',
    rgb: JSON.stringify({ r: 232, g: 228, b: 220 }),
    finish: 'Mat',
    productLine: 'Profi-DIN',
    type: 'Interior',
    coverage: 13,
    price: 52.95,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Herbol',
    name: 'Herbol Profi-DIN',
    colorCode: '234',
    colorName: 'Soft Blue',
    hexColor: '#D0DCE5',
    rgb: JSON.stringify({ r: 208, g: 220, b: 229 }),
    finish: 'Mat',
    productLine: 'Profi-DIN',
    type: 'Interior',
    coverage: 13,
    price: 52.95,
    popular: false,
    inStock: true,
  },

  // ========== ADDITIONAL POPULAR COLORS ==========

  // Donkere kleuren
  {
    brand: 'Sikkens',
    name: 'Alpha Rezisto',
    colorCode: 'L1.05.40',
    colorName: 'Antraciet',
    hexColor: '#6B6B6B',
    rgb: JSON.stringify({ r: 107, g: 107, b: 107 }),
    finish: 'Mat',
    productLine: 'Alpha Rezisto',
    type: 'Interior',
    coverage: 12,
    price: 45.95,
    popular: true,
    inStock: true,
  },
  {
    brand: 'Sigma',
    name: 'Sigma S3000',
    colorCode: 'S 8505-R80B',
    colorName: 'Donker Blauw',
    hexColor: '#2C3E50',
    rgb: JSON.stringify({ r: 44, g: 62, b: 80 }),
    finish: 'Mat',
    productLine: 'S3000',
    type: 'Interior',
    coverage: 10,
    price: 42.50,
    popular: true,
    inStock: true,
  },
  {
    brand: 'Trimetal',
    name: 'Histor Perfect Finish',
    colorCode: '6243',
    colorName: 'Forest Green',
    hexColor: '#3D5A45',
    rgb: JSON.stringify({ r: 61, g: 90, b: 69 }),
    finish: 'Mat',
    productLine: 'Perfect Finish',
    type: 'Interior',
    coverage: 11,
    price: 39.95,
    popular: false,
    inStock: true,
  },

  // Warme accentkleuren
  {
    brand: 'Herbol',
    name: 'Herbol Profi-DIN',
    colorCode: '312',
    colorName: 'Terracotta',
    hexColor: '#CD853F',
    rgb: JSON.stringify({ r: 205, g: 133, b: 63 }),
    finish: 'Mat',
    productLine: 'Profi-DIN',
    type: 'Interior',
    coverage: 13,
    price: 52.95,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Sikkens',
    name: 'Alpha Rezisto',
    colorCode: 'H4.30.40',
    colorName: 'Warm Koraal',
    hexColor: '#BFA094',
    rgb: JSON.stringify({ r: 191, g: 160, b: 148 }),
    finish: 'Mat',
    productLine: 'Alpha Rezisto',
    type: 'Interior',
    coverage: 12,
    price: 45.95,
    popular: false,
    inStock: true,
  },

  // ========== EXTRA KLEUREN VOOR STIJLEN ==========

  // Blauwtinten
  {
    brand: 'Sigma',
    name: 'Sigma S3000',
    colorCode: 'S 8005-R80B',
    colorName: 'Navy Blauw',
    hexColor: '#00008B',
    rgb: JSON.stringify({ r: 0, g: 0, b: 139 }),
    finish: 'Mat',
    productLine: 'S3000',
    type: 'Interior',
    coverage: 10,
    price: 42.50,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Trimetal',
    name: 'Histor Perfect Finish',
    colorCode: '7612',
    colorName: 'Licht Hemelsblauw',
    hexColor: '#87CEEB',
    rgb: JSON.stringify({ r: 135, g: 206, b: 235 }),
    finish: 'Mat',
    productLine: 'Perfect Finish',
    type: 'Interior',
    coverage: 11,
    price: 39.95,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Herbol',
    name: 'Herbol Profi-DIN',
    colorCode: '425',
    colorName: 'Royaal Blauw',
    hexColor: '#4169E1',
    rgb: JSON.stringify({ r: 65, g: 105, b: 225 }),
    finish: 'Mat',
    productLine: 'Profi-DIN',
    type: 'Interior',
    coverage: 13,
    price: 52.95,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Sigma',
    name: 'Sigma S3000',
    colorCode: 'S 4050-B50G',
    colorName: 'Turquoise Blauw',
    hexColor: '#20B2AA',
    rgb: JSON.stringify({ r: 32, g: 178, b: 170 }),
    finish: 'Mat',
    productLine: 'S3000',
    type: 'Interior',
    coverage: 10,
    price: 42.50,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Sikkens',
    name: 'Alpha Rezisto',
    colorCode: 'B0.20.50',
    colorName: 'Staalblauw',
    hexColor: '#4682B4',
    rgb: JSON.stringify({ r: 70, g: 130, b: 180 }),
    finish: 'Mat',
    productLine: 'Alpha Rezisto',
    type: 'Interior',
    coverage: 12,
    price: 45.95,
    popular: false,
    inStock: true,
  },

  // Groentinten
  {
    brand: 'Trimetal',
    name: 'Histor Perfect Finish',
    colorCode: '6341',
    colorName: 'Bosgroen',
    hexColor: '#228B22',
    rgb: JSON.stringify({ r: 34, g: 139, b: 34 }),
    finish: 'Mat',
    productLine: 'Perfect Finish',
    type: 'Interior',
    coverage: 11,
    price: 39.95,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Herbol',
    name: 'Herbol Profi-DIN',
    colorCode: '568',
    colorName: 'Olijfgroen',
    hexColor: '#556B2F',
    rgb: JSON.stringify({ r: 85, g: 107, b: 47 }),
    finish: 'Mat',
    productLine: 'Profi-DIN',
    type: 'Interior',
    coverage: 13,
    price: 52.95,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Sigma',
    name: 'Sigma S3000',
    colorCode: 'S 6020-G10Y',
    colorName: 'Donker Groen Grijs',
    hexColor: '#2F4F4F',
    rgb: JSON.stringify({ r: 47, g: 79, b: 79 }),
    finish: 'Mat',
    productLine: 'S3000',
    type: 'Interior',
    coverage: 10,
    price: 42.50,
    popular: false,
    inStock: true,
  },

  // Geeltinten
  {
    brand: 'Sikkens',
    name: 'Alpha Rezisto',
    colorCode: 'Y1.20.80',
    colorName: 'Licht Khaki',
    hexColor: '#F0E68C',
    rgb: JSON.stringify({ r: 240, g: 230, b: 140 }),
    finish: 'Mat',
    productLine: 'Alpha Rezisto',
    type: 'Interior',
    coverage: 12,
    price: 45.95,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Trimetal',
    name: 'Histor Perfect Finish',
    colorCode: '6152',
    colorName: 'Goud Geel',
    hexColor: '#FFD700',
    rgb: JSON.stringify({ r: 255, g: 215, b: 0 }),
    finish: 'Mat',
    productLine: 'Perfect Finish',
    type: 'Interior',
    coverage: 11,
    price: 39.95,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Herbol',
    name: 'Herbol Profi-DIN',
    colorCode: '625',
    colorName: 'Klassiek Goud',
    hexColor: '#D4AF37',
    rgb: JSON.stringify({ r: 212, g: 175, b: 55 }),
    finish: 'Mat',
    productLine: 'Profi-DIN',
    type: 'Interior',
    coverage: 13,
    price: 52.95,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Sigma',
    name: 'Sigma S3000',
    colorCode: 'S 2060-Y',
    colorName: 'Goudstaaf',
    hexColor: '#DAA520',
    rgb: JSON.stringify({ r: 218, g: 165, b: 32 }),
    finish: 'Mat',
    productLine: 'S3000',
    type: 'Interior',
    coverage: 10,
    price: 42.50,
    popular: false,
    inStock: true,
  },

  // Rood/Oranje tinten
  {
    brand: 'Sikkens',
    name: 'Alpha Rezisto',
    colorCode: 'R3.40.50',
    colorName: 'Tomaat Rood',
    hexColor: '#FF6347',
    rgb: JSON.stringify({ r: 255, g: 99, b: 71 }),
    finish: 'Mat',
    productLine: 'Alpha Rezisto',
    type: 'Interior',
    coverage: 12,
    price: 45.95,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Trimetal',
    name: 'Histor Perfect Finish',
    colorCode: '6442',
    colorName: 'Karmozijn Rood',
    hexColor: '#DC143C',
    rgb: JSON.stringify({ r: 220, g: 20, b: 60 }),
    finish: 'Mat',
    productLine: 'Perfect Finish',
    type: 'Interior',
    coverage: 11,
    price: 39.95,
    popular: false,
    inStock: true,
  },

  // Paars tinten
  {
    brand: 'Herbol',
    name: 'Herbol Profi-DIN',
    colorCode: '745',
    colorName: 'Medium Paars',
    hexColor: '#9370DB',
    rgb: JSON.stringify({ r: 147, g: 112, b: 219 }),
    finish: 'Mat',
    productLine: 'Profi-DIN',
    type: 'Interior',
    coverage: 13,
    price: 52.95,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Sigma',
    name: 'Sigma S3000',
    colorCode: 'S 4040-R40B',
    colorName: 'Violet Paars',
    hexColor: '#8B4789',
    rgb: JSON.stringify({ r: 139, g: 71, b: 137 }),
    finish: 'Mat',
    productLine: 'S3000',
    type: 'Interior',
    coverage: 10,
    price: 42.50,
    popular: false,
    inStock: true,
  },

  // Bruintinten
  {
    brand: 'Sikkens',
    name: 'Alpha Rezisto',
    colorCode: 'Y4.30.40',
    colorName: 'Zadelbruin',
    hexColor: '#8B4513',
    rgb: JSON.stringify({ r: 139, g: 69, b: 19 }),
    finish: 'Mat',
    productLine: 'Alpha Rezisto',
    type: 'Interior',
    coverage: 12,
    price: 45.95,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Trimetal',
    name: 'Histor Perfect Finish',
    colorCode: '6227',
    colorName: 'Warm Beige Bruin',
    hexColor: '#DEB887',
    rgb: JSON.stringify({ r: 222, g: 184, b: 135 }),
    finish: 'Mat',
    productLine: 'Perfect Finish',
    type: 'Interior',
    coverage: 11,
    price: 39.95,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Herbol',
    name: 'Herbol Profi-DIN',
    colorCode: '156',
    colorName: 'Chocolade Bruin',
    hexColor: '#D2691E',
    rgb: JSON.stringify({ r: 210, g: 105, b: 30 }),
    finish: 'Mat',
    productLine: 'Profi-DIN',
    type: 'Interior',
    coverage: 13,
    price: 52.95,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Sigma',
    name: 'Sigma S3000',
    colorCode: 'S 6020-Y50R',
    colorName: 'Taupe Bruin',
    hexColor: '#8B7355',
    rgb: JSON.stringify({ r: 139, g: 115, b: 85 }),
    finish: 'Mat',
    productLine: 'S3000',
    type: 'Interior',
    coverage: 10,
    price: 42.50,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Sikkens',
    name: 'Alpha Rezisto',
    colorCode: 'Y5.10.50',
    colorName: 'Grijs Bruin',
    hexColor: '#8B7D6B',
    rgb: JSON.stringify({ r: 139, g: 125, b: 107 }),
    finish: 'Mat',
    productLine: 'Alpha Rezisto',
    type: 'Interior',
    coverage: 12,
    price: 45.95,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Trimetal',
    name: 'Histor Perfect Finish',
    colorCode: '6156',
    colorName: 'Tarweblond',
    hexColor: '#F5DEB3',
    rgb: JSON.stringify({ r: 245, g: 222, b: 179 }),
    finish: 'Mat',
    productLine: 'Perfect Finish',
    type: 'Interior',
    coverage: 11,
    price: 39.95,
    popular: false,
    inStock: true,
  },

  // Extra grijs/zwart tinten
  {
    brand: 'Herbol',
    name: 'Herbol Profi-DIN',
    colorCode: '089',
    colorName: 'Dim Grijs',
    hexColor: '#696969',
    rgb: JSON.stringify({ r: 105, g: 105, b: 105 }),
    finish: 'Mat',
    productLine: 'Profi-DIN',
    type: 'Interior',
    coverage: 13,
    price: 52.95,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Sigma',
    name: 'Sigma S3000',
    colorCode: 'S 9000-N',
    colorName: 'Zwart',
    hexColor: '#000000',
    rgb: JSON.stringify({ r: 0, g: 0, b: 0 }),
    finish: 'Mat',
    productLine: 'S3000',
    type: 'Interior',
    coverage: 10,
    price: 42.50,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Sikkens',
    name: 'Alpha Rezisto',
    colorCode: 'L1.10.70',
    colorName: 'Zilver Grijs',
    hexColor: '#C0C0C0',
    rgb: JSON.stringify({ r: 192, g: 192, b: 192 }),
    finish: 'Mat',
    productLine: 'Alpha Rezisto',
    type: 'Interior',
    coverage: 12,
    price: 45.95,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Trimetal',
    name: 'Histor Perfect Finish',
    colorCode: '7539',
    colorName: 'Medium Grijs',
    hexColor: '#808080',
    rgb: JSON.stringify({ r: 128, g: 128, b: 128 }),
    finish: 'Mat',
    productLine: 'Perfect Finish',
    type: 'Interior',
    coverage: 11,
    price: 39.95,
    popular: false,
    inStock: true,
  },
  {
    brand: 'Herbol',
    name: 'Herbol Profi-DIN',
    colorCode: '123',
    colorName: 'Licht Gainsboro',
    hexColor: '#D3D3D3',
    rgb: JSON.stringify({ r: 211, g: 211, b: 211 }),
    finish: 'Mat',
    productLine: 'Profi-DIN',
    type: 'Interior',
    coverage: 13,
    price: 52.95,
    popular: false,
    inStock: true,
  },
];

async function main() {
  console.log('🎨 Starting paint products seed...');

  // Clear existing products
  await prisma.paintProduct.deleteMany({});
  console.log('✓ Cleared existing paint products');

  // Insert paint products
  let inserted = 0;
  for (const product of paintProducts) {
    await prisma.paintProduct.create({
      data: product,
    });
    inserted++;
  }

  console.log(`✓ Inserted ${inserted} paint products`);
  console.log('\n📊 Summary by brand:');

  const brands = ['Sikkens', 'Sigma', 'Trimetal', 'Herbol'];
  for (const brand of brands) {
    const count = paintProducts.filter(p => p.brand === brand).length;
    console.log(`  ${brand}: ${count} products`);
  }

  console.log('\n✅ Seed completed successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
